#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry|odysee)
#         https://www.youtube.com/user/gotbletu
# DESC:   launch other fzf scripts in tmux
# DEMO:   https://youtu.be/41JxYe70Xwo
# REQD:   bind-key for tmux
#         $EDITOR ~/.tmux.conf
#         # tmux -V >= 3.2+
#         bind-key Tab capture-pane \; save-buffer /tmp/tmux-buffer \; delete-buffer \; display-popup -w 80% -h 60% -E "/path/to/fzf-speed"
#
#         # tmux -V < 3.2
#         bind-key Tab capture-pane \; save-buffer /tmp/tmux-buffer \; delete-buffer \; split-window -Z "/path/to/fzf-speed"
#         bind-key Tab capture-pane \; save-buffer /tmp/tmux-buffer \; delete-buffer \; split-window "/path/to/fzf-speed"

# https://askubuntu.com/questions/993078/what-does-0-in-shell-scripts-do
DIR="${0%/*}"

SELECTED="$(find "$DIR" -maxdepth 1 -type f -exec basename {} \; | sort | grep '^_' | sed 's@\.@ @g' | column -s ',' -t |  fzf -e -i --bind alt-enter:toggle-preview --prompt="fzf-speed: " --info=default --layout=reverse --preview-window left:wrap --preview "echo {} | cut -d ' ' -f1 | xargs -I % find $DIR -name '%*' | xargs -I xx bat --color=always --language bash --plain xx " | cut -d ' ' -f1)"
eval "${DIR}/${SELECTED},*"
